project:
  title: "Bayesian Data Analysis"
  type: website
  output-dir: .
website:
  page-navigation: true
  # back-to-top-navigation: true
  sidebar:
    style: "docked"
    contents:
      - section: "General instructions"
        contents: "{assignment_instructions,docker}.qmd"
      - text: "---"
      - section: "Assignments"
        contents: "{assignment{1,2,3,4,5,6,7,8,9}}*.qmd"
      - text: "---"
      - section: "Templates"
        contents: "{template{1,2,3,4,5,6,7,8,9}}*.qmd"
format: 
  html:
    page-layout: article
execute:
  freeze: auto
  error: true # uncomment this to stop quarto abort on error