project:
  title: "Bayesian Data Analysis"
  type: website
  output-dir: .
website:
  sidebar:
    href: "https://avehtari.github.io/BDA_course_Aalto/Aalto2023.html"
    style: "docked"
    contents: "{docker,assignment{1,2,3,4,5,6,7,8,9}}*.qmd"
format: 
  html:
    page-layout: article
execute:
  freeze: auto
  error: true # uncomment this to stop quarto abort on error