project:
  title: "Bayesian Data Analysis"
  type: website
  output-dir: .
website:
  sidebar:
    style: "docked"
    contents: "*.qmd"
format: 
  html:
    page-layout: full
execute:
  freeze: auto
  # error: true # uncomment this to stop quarto abort on error