on:
  push:
    branches:
      - render-replace
    # paths: ['**.Rmd']

name: Render and Publish Website

permissions:
  contents: write
  pages: write

jobs:
  render-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
              any::rmarkdown
              any::sessioninfo
              any::tidyr
              local::rpackage
              github::stan-dev/cmdstanr

      # _site.yml file configured to render website to the _site folder,
      # which is the expected location for the Quarto publish step
      - name: Render Main Rmarkdown Website
        run: rmarkdown::render_site()
        shell: Rscript {0}

      # Assignments _quarto.yml file configured to render website to the
      # _site/assignments folder
      - name: Render Assignments Quarto Sub-website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: assignments

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          keep_files: true
          publish_dir: _site
