on:
  push:
    branches:
      - token-tests
    # paths: ['**.Rmd']

name: Render and Publish Website

permissions:
  contents: write
  pages: write

jobs:
  render-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN}}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::tidyr

      - name: Render and Publish Website
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
